region            = "ap-south-1"
environment       = "qa"
vpc_cidr          = "10.1.0.0/16"
subnet_cidr       = "10.1.1.0/24"
availability_zone = "ap-south-1a"
bucket_name       = "sanjana-lambda-code-bucket"
