region            = "ap-south-1"
environment       = "dev"
vpc_cidr          = "10.0.0.0/16"
subnet_cidr       = "10.0.1.0/24"
availability_zone = "ap-south-1a"
bucket_name       = "sanjana-lambda-code-bucket"
